networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  storage_admin:
    driver: local
  storage_api:
    driver: local

services:
  # NGINX for Admin Panel
  nginx-admin:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - NGINX_CONF=admin.default.conf
    restart: unless-stopped
    container_name: nginx-admin
    ports:
      - 8000:80
    volumes:
      - "./admin-panel:/var/www/html:delegated"
      - "./env/admin_panel.env:/var/www/html/.env"
    depends_on:
      - php-admin
      - database
      - admin-queue
      - admin-cron
    networks:
      - laravel

  # PHP for Admin Panel
  php-admin:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: php-admin
    volumes:
      - "./admin-panel:/var/www/html:delegated"
      - "./env/admin_panel.env:/var/www/html/.env"
      - "./admin-panel/storage:/var/www/html/storage"
      - "/var/run/docker.sock:/var/run/docker.sock" # دسترسی به Docker daemon
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # NGINX for API Service
  nginx-api:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - NGINX_CONF=api.default.conf
    restart: unless-stopped
    container_name: nginx-api
    ports:
      - 8001:80
    volumes:
      - "./api-service:/var/www/html:delegated"
      - "./env/api_service.env:/var/www/html/.env"
    depends_on:
      - php-api
      - api-queue
      - api-cron
    networks:
      - laravel

  # PHP for API Service
  php-api:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: php-api
    restart: unless-stopped
    volumes:
      - "./api-service:/var/www/html:delegated"
      - "./env/api_service.env:/var/www/html/.env"
      - "./api-service/storage:/var/www/html/storage"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MySQL Database (Single Instance for both systems)
  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./dockerfiles/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

  # Laravel Cron Jobs
  admin-cron:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: admin-cron
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: /bin/sh -c "while true; do php artisan schedule:run --verbose; sleep 60; done"
    networks:
      - laravel

  api-cron:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: api-cron
    volumes:
      - "./api-service:/var/www/html:delegated"
      - "./env/api_service.env:/var/www/html/.env"
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: /bin/sh -c "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Laravel Queue Workers
  admin-queue:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: admin-queue
    restart: unless-stopped
    volumes:
      - "./admin-panel:/var/www/html:delegated"
      - "./env/admin_panel.env:/var/www/html/.env"
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint:
      [
        "php",
        "/var/www/html/artisan",
        "queue:work",
        "--tries=20",
        "--timeout=3700",
        "--queue=default,admin-email,hd-wallet-sync,admin-withdrawal,admin-withdrawal-check",
      ]
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-queue:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: api-queue
    volumes:
      - "./api-service:/var/www/html:delegated"
      - "./env/api_service.env:/var/www/html/.env"
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint:
      [
        "php",
        "/var/www/html/artisan",
        "queue:work",
        "--tries=20",
        "--timeout=60",
        "--queue=api-service,api-email,api-withdrawal,api-withdrawal-check",
      ]
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Laravel Queue Workers
  exchange-listen:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-f}
    container_name: exchange-listen
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
      - redis
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan", "exchange:listen"]
    networks:
      - laravel
    restart: always

  admin-reverb:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-f}
    container_name: admin-reverb
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
      - redis
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan", "reverb:start"]
    ports:
      - 8081:8080
    networks:
      - laravel
    restart: always

  # Composer service for Admin Panel
  composer-admin:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: composer-admin
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php-admin
    profiles: ["composer"]
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - laravel

  # Composer service for API Service
  composer-api:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: composer-api
    volumes:
      - ./api-service:/var/www/html:delegated
      - ./env/api_service.env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php-api
    profiles: ["composer"]
    entrypoint: ["composer", "--ignore-platform-reqs"]

  artisan-admin:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: artisan-admin
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
    depends_on:
      - database

  artisan-api:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: artisan-api
    volumes:
      - ./api-service:/var/www/html:delegated
      - ./env/api_service.env:/var/www/html/.env
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./admin-panel:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: ["npm"]
    entrypoint: ["npm"]
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - laravel
