networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local

services:
  # NGINX for Admin Panel
  nginx-admin:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    restart: unless-stopped
    container_name: nginx-admin
    ports:
      - 8000:80
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
      - ./admin-panel/storage:/var/www/html/storage
    depends_on:
      - php-admin
      - database
      - laravel-queue
      - laravel-cron
#      - phpmyadmin
    networks:
      - laravel

  # PHP for Admin Panel
  php-admin:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: php-admin
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
      - ./admin-panel/storage:/var/www/html/storage
    networks:
      - laravel

  # NGINX for API Service
  nginx-api:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    restart: unless-stopped
    container_name: nginx-api
    ports:
      - 8001:80
    volumes:
      - ./api-service:/var/www/html:delegated
      - ./env/api_service.env:/var/www/html/.env
      - ./api-service/storage:/var/www/html/storage
    depends_on:
      - php-api
      - database
      - laravel-queue
      - laravel-cron
    networks:
      - laravel

  # PHP for API Service
  php-api:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: php-api
    volumes:
      - ./api-service:/var/www/html:delegated
      - ./env/api_service.env:/var/www/html/.env
      - ./api-service/storage:/var/www/html/storage
    networks:
      - laravel


  # MySQL Database
  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel


  # Laravel Cron Jobs
  laravel-cron:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: laravel-cron
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan', 'schedule:work' ]
    networks:
      - laravel

  # Laravel Queue Workers
  laravel-queue:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: laravel-queue
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan', 'queue:work' ]
    networks:
      - laravel

  laravel-migrate-seed:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: laravel-migrate-seed
    volumes:
      - ./admin-panel:/var/www/html:delegated
      - ./env/admin_panel.env:/var/www/html/.env
    depends_on:
      - database
    profiles: [ "migrate-seed" ]
    working_dir: /var/www/html
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        php artisan migrate
        php artisan db:seed
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: composer
    volumes:
#      - ./admin-panel:/var/www/html:delegated
#      - ./env/admin_panel.env:/var/www/html/.env
      - ./admin-panel:/var/www/html/admin-panel:delegated
      - ./api-service:/var/www/html/api-service:delegated
      - ./env/admin_panel.env:/var/www/html/admin-panel/.env
      - ./env/api_service.env:/var/www/html/api-service/.env
    working_dir: /var/www/html
    depends_on:
      - php-admin
      - php-api

    profiles: [ "composer" ]
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  artisan-admin:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: artisan-admin
    volumes:
      - ./admin-panel:/var/www/html/admin-panel:delegated
      - ./env/admin_panel.env:/var/www/html/admin-panel/.env
    working_dir: /var/www/html/admin-panel
    entrypoint: [ 'php', '/var/www/html/admin-panel/artisan' ]
    networks:
      - laravel
    depends_on:
      - database

  artisan-api:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laraveluser}
    container_name: artisan-api
    volumes:
      - ./api-service:/var/www/html/api-service:delegated
      - ./env/api_service.env:/var/www/html/api-service/.env
    working_dir: /var/www/html/api-service
    entrypoint: [ 'php', '/var/www/html/api-service/artisan' ]
    networks:
      - laravel
    depends_on:
      - database

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./admin-panel:/var/www/html
    #      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: [ "npm" ]
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  #
  #    redis:
  #        image: redis:alpine
  #        container_name: redis
  #        restart: unless-stopped
  #        ports:
  #            - 6380:6379
  #        networks:
  #            - laravel

    #  phpmyadmin:
    #    image: phpmyadmin:5.2.0
    #    container_name: phpmyadmin
    #    env_file:
    #      - ./env/phpmyadmin.env
    #    depends_on:
    #      - database
    #    ports:
    #      - 8888:80
    #    networks:
    #      - laravel